//
// Created by codgician on 12/22/2017.
//

#ifndef C_FINAL_EXAM_MACRO_H
#define C_FINAL_EXAM_MACRO_H

// Process bool type
#include <stdbool.h>
#define bool _Bool

// Define error status
#define SUCCESS 0x01

#define ERROR_INVALID_PRICE_TYPE 0x02
#define ERROR_INVALID_ROOM_TYPE 0x03

#define ERROR_INVALID_HOUR_PRICE 0x04
#define ERROR_INVALID_DAY_PRICE 0x05

#define ERROR_INVALID_DURATION 0x06

#define ERROR_INVALID_YEAR 0x07
#define ERROR_INVALID_MONTH 0x08
#define ERROR_INVALID_DAY 0x09
#define ERROR_INVALID_HOUR 0x10

#define ERROR_START_DATETIME_LARGER_THAN_END_DATETIME 0x11

#define ERR_INPUT_ISBLANK 0x12
#define ERR_INPUT_ISINVALID 0X13

#endif //C_FINAL_EXAM_MACRO_H
